version: '3.3'
services:
  onelist:
    restart: always
    container_name: onelist
    image: 'maotsuai/onelist:latest'
    volumes:
      - '/root/onelist/config:/config'
    ports:
      - '5245:5245'
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
    extra_hosts:
      - 'api.themoviedb.org:108.156.46.87'
      - 'api.themoviedb.org:108.156.46.80'
      - 'api.themoviedb.org:108.156.46.56'
      - 'api.themoviedb.org:108.156.46.129'
      - 'image.tmdb.org:108.138.233.53'
      - 'image.tmdb.org:108.138.233.12'
      - 'image.tmdb.org:108.138.233.46'
      - 'image.tmdb.org:108.138.233.88'
      - 'www.themoviedb.org:108.157.78.18'
      - 'www.themoviedb.org:108.157.78.94'
      - 'www.themoviedb.org:108.157.78.103'
      - 'www.themoviedb.org:108.157.78.116'
